# Generated by Django 4.2.7 on 2025-07-27 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('truck_number', models.CharField(max_length=100)),
                ('trailer_number', models.CharField(max_length=100)),
                ('carrier_name', models.CharField(max_length=255)),
                ('home_terminal_timezone', models.CharField(max_length=50)),
                ('shipping_document_numbers', models.TextField()),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_hours_used', models.FloatField()),
                ('log_sheet', models.TextField()),
                ('remaining_driving_hours', models.FloatField()),
                ('remaining_on_duty_hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Off Duty', 'Off Duty'), ('Sleeper Berth', 'Sleeper Berth'), ('Driving', 'Driving'), ('On Duty (Not Driving)', 'On Duty (Not Driving)')], max_length=25)),
                ('order', models.PositiveIntegerField(default=0)),
                ('eld_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_status_changes', to='eld_logs.eldlog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
