services:
  - type: web
    name: trucklogix-backend
    region: oregon
    plan: free
    env: python
    rootDirectory: backend
    buildCommand: "cd backend && bash .render-build.sh"
    startCommand: "cd backend && bash start.sh"
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here 
      - key: DEBUG
        value: "False"
      - key: OPENROUTESERVICE_API_KEY
        value: eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjExNmMwZmM2NjFiMjQzMzU4NWIyZWZiODAwZTAyMzc1IiwiaCI6Im11cm11cjY0In0=
      - key: PORT
        value: "8000"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: PYTHON_VERSION
        value: "3.10.11"
      