# Generated by Django 4.2.7 on 2025-07-27 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours_used', models.FloatField()),
                ('optimized_route', models.TextField()),
                ('estimated_travel_time', models.CharField(max_length=100)),
                ('estimated_fuel_consumption', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestBreakStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('route_optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_break_stops', to='routes.routeoptimization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('route_optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='routes.routeoptimization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
